//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference4
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tag", Namespace="http://schemas.datacontract.org/2004/07/ScadaCore.Tags.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference4.InputTag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference4.AnalogInputTag))]
    public partial class Tag : object
    {
        
        private string DescriptionField;
        
        private string IOAddressField;
        
        private string IdField;
        
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IOAddress
        {
            get
            {
                return this.IOAddressField;
            }
            set
            {
                this.IOAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputTag", Namespace="http://schemas.datacontract.org/2004/07/ScadaCore.Tags.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference4.AnalogInputTag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference4.Tag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference4.Tag[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference4.AnalogInputTag[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference4.Unit))]
    public partial class InputTag : ServiceReference4.Tag
    {
        
        private object DriverField;
        
        private bool IsScanOnField;
        
        private int ScanTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Driver
        {
            get
            {
                return this.DriverField;
            }
            set
            {
                this.DriverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsScanOn
        {
            get
            {
                return this.IsScanOnField;
            }
            set
            {
                this.IsScanOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScanTime
        {
            get
            {
                return this.ScanTimeField;
            }
            set
            {
                this.ScanTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalogInputTag", Namespace="http://schemas.datacontract.org/2004/07/ScadaCore.Tags.Model")]
    public partial class AnalogInputTag : ServiceReference4.InputTag
    {
        
        private double HighLimitField;
        
        private double LowLimitField;
        
        private ServiceReference4.Unit UnitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HighLimit
        {
            get
            {
                return this.HighLimitField;
            }
            set
            {
                this.HighLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LowLimit
        {
            get
            {
                return this.LowLimitField;
            }
            set
            {
                this.LowLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference4.Unit Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unit", Namespace="http://schemas.datacontract.org/2004/07/ScadaCore.Tags.Model")]
    public enum Unit : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kg = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ms = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.ITagService")]
    public interface ITagService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/AddTag", ReplyAction="http://tempuri.org/ITagService/AddTagResponse")]
        System.Threading.Tasks.Task AddTagAsync(ScadaCore.Tags.Model.Tag tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/RemoveTag", ReplyAction="http://tempuri.org/ITagService/RemoveTagResponse")]
        System.Threading.Tasks.Task RemoveTagAsync(string tagId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/EnableScan", ReplyAction="http://tempuri.org/ITagService/EnableScanResponse")]
        System.Threading.Tasks.Task EnableScanAsync(string tagId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/DisableScan", ReplyAction="http://tempuri.org/ITagService/DisableScanResponse")]
        System.Threading.Tasks.Task DisableScanAsync(string tagId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/SetOutputValue", ReplyAction="http://tempuri.org/ITagService/SetOutputValueResponse")]
        System.Threading.Tasks.Task SetOutputValueAsync(string tagId, double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAllTags", ReplyAction="http://tempuri.org/ITagService/GetAllTagsResponse")]
        System.Threading.Tasks.Task<ServiceReference4.Tag[]> GetAllTagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagService/GetAnalogInputTags", ReplyAction="http://tempuri.org/ITagService/GetAnalogInputTagsResponse")]
        System.Threading.Tasks.Task<ServiceReference4.AnalogInputTag[]> GetAnalogInputTagsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ITagServiceChannel : ServiceReference4.ITagService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class TagServiceClient : System.ServiceModel.ClientBase<ServiceReference4.ITagService>, ServiceReference4.ITagService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TagServiceClient() : 
                base(TagServiceClient.GetDefaultBinding(), TagServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITagService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TagServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TagServiceClient.GetBindingForEndpoint(endpointConfiguration), TagServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TagServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TagServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TagServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TagServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TagServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AddTagAsync(ScadaCore.Tags.Model.Tag tag)
        {
            return base.Channel.AddTagAsync(tag);
        }
        
        public System.Threading.Tasks.Task RemoveTagAsync(string tagId)
        {
            return base.Channel.RemoveTagAsync(tagId);
        }
        
        public System.Threading.Tasks.Task EnableScanAsync(string tagId)
        {
            return base.Channel.EnableScanAsync(tagId);
        }
        
        public System.Threading.Tasks.Task DisableScanAsync(string tagId)
        {
            return base.Channel.DisableScanAsync(tagId);
        }
        
        public System.Threading.Tasks.Task SetOutputValueAsync(string tagId, double value)
        {
            return base.Channel.SetOutputValueAsync(tagId, value);
        }
        
        public System.Threading.Tasks.Task<ServiceReference4.Tag[]> GetAllTagsAsync()
        {
            return base.Channel.GetAllTagsAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference4.AnalogInputTag[]> GetAnalogInputTagsAsync()
        {
            return base.Channel.GetAnalogInputTagsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITagService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITagService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64310/DatabaseManagementService/TagService.svc/Alarm");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TagServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITagService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TagServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITagService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITagService,
        }
    }
}
